import React, { useState, useEffect, useMemo } from 'react';
import { Navbar, TabType } from './components/Navbar';
import { DailyGacha } from './components/DailyGacha';
import { ConstellationMap } from './components/ConstellationMap';
import { DomainExplorer } from './components/DomainExplorer';
import { GoogleSheetTable } from './components/GoogleSheetTable';
import { WhyModal } from './components/WhyModal';
import { CompleteModal } from './components/CompleteModal';
import { AIGeneratorModal } from './components/AIGeneratorModal';
import { Milestone, SheetRecord, Domain } from './types';
import { getAll1000Milestones, getMilestoneById } from './data/generatorEngine';
import { DOMAINS } from './data/domains';
import { sounds } from './utils/sound';

const STORAGE_KEY = 'saigon_1000_milestones_records_v1';
const FIRST_VISIT_KEY = 'saigon_1000_milestones_seen_why_v1';

// Seed sample records so the board is lively right away
const INITIAL_RECORDS: SheetRecord[] = [
  {
    id: 152,
    ticketText: '[Vào 1 quán có 2 màu, hỏi chủ quán 1 câu] + [Quán nước ven đường] + [Phát hiện chủ quán cũng cùng quê miền Trung/Tây với mình]',
    feeling: 'Cô chủ quán cùng quê Quảng Ngãi, nói chuyện 5 phút tự nhiên hết nhớ nhà!',
    wantRedo: true,
    completedAt: 'Hôm qua, 17:45'
  },
  {
    id: 1,
    ticketText: '[Đi bộ theo hướng rẽ phải 3 lần liên tiếp] + [Hẻm cụt đường Hoàng Sa / Trường Sa] + [Phát hiện một quán hủ tiếu gõ giấu mình cực thơm ngon]',
    feeling: 'Đầu óc nhẹ bẫng sau 8 tiếng cày máy tính, hủ tiếu 25k ngon bất ngờ.',
    wantRedo: true,
    completedAt: 'Hôm nay, 08:30'
  },
  {
    id: 701,
    ticketText: '[Gấp chiếc mền và vuốt phẳng ga giường ngay khi thức dậy] + [Chiếc giường ngủ trong phòng trọ] + [Chiến thắng nhỏ đầu tiên trong ngày tạo đà cho chuỗi năng suất cao]',
    feeling: 'Căn phòng trọ 15m² nhìn tươm tất hẳn, tự hào về bản thân.',
    wantRedo: true,
    completedAt: 'Hôm nay, 07:15'
  }
];

export default function App() {
  const [activeTab, setActiveTab] = useState<TabType>('gacha');
  const [records, setRecords] = useState<SheetRecord[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        return JSON.parse(saved);
      }
    } catch {
      // fallback
    }
    return INITIAL_RECORDS;
  });

  const [currentMilestone, setCurrentMilestone] = useState<Milestone>(() => {
    return getMilestoneById(152); // default to milestone 152 described in user prompt
  });

  const [whyModalOpen, setWhyModalOpen] = useState(false);
  const [completeModalMilestone, setCompleteModalMilestone] = useState<Milestone | null>(null);
  const [aiGeneratorDomain, setAiGeneratorDomain] = useState<Domain | null>(null);
  const [soundEnabled, setSoundEnabled] = useState(true);

  // Show why modal on first visit
  useEffect(() => {
    try {
      const seen = localStorage.getItem(FIRST_VISIT_KEY);
      if (!seen) {
        setWhyModalOpen(true);
        localStorage.setItem(FIRST_VISIT_KEY, 'true');
      }
    } catch {
      // ignore
    }
  }, []);

  // Save records to LocalStorage
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(records));
    } catch (e) {
      console.error('Failed to save records to localStorage', e);
    }
  }, [records]);

  // Set of completed IDs
  const completedMilestoneIds = useMemo(() => {
    return new Set<number>(records.map((r) => r.id));
  }, [records]);

  // All 1000 milestones
  const allMilestones = useMemo(() => {
    const list = getAll1000Milestones();
    return list.map((m) => {
      const rec = records.find((r) => r.id === m.id);
      return {
        ...m,
        isCompleted: Boolean(rec),
        feeling: rec?.feeling,
        wantRedo: rec?.wantRedo,
        completedAt: rec?.completedAt
      };
    });
  }, [records]);

  // Handler: save completion
  const handleSaveComplete = (id: number, feeling: string, wantRedo: boolean) => {
    const now = new Date();
    const timeStr = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}, ${now.getDate()}/${now.getMonth() + 1}`;
    
    const milestone = getMilestoneById(id);
    const newRecord: SheetRecord = {
      id,
      ticketText: milestone.title,
      feeling,
      wantRedo,
      completedAt: timeStr
    };

    setRecords((prev) => {
      const filtered = prev.filter((r) => r.id !== id);
      return [newRecord, ...filtered];
    });

    sounds.playComplete();
  };

  // Handler: update record in Sheet
  const handleUpdateRecord = (id: number, feeling: string, wantRedo: boolean | null) => {
    setRecords((prev) =>
      prev.map((r) => (r.id === id ? { ...r, feeling, wantRedo } : r))
    );
  };

  // Handler: delete record from Sheet
  const handleDeleteRecord = (id: number) => {
    setRecords((prev) => prev.filter((r) => r.id !== id));
  };

  // Handler: add custom milestones generated by AI
  const handleAddCustomMilestones = (customList: Milestone[]) => {
    // Optionally set first item as current
    if (customList.length > 0) {
      setCurrentMilestone(customList[0]);
      setActiveTab('gacha');
    }
  };

  // Toggle sound
  const handleToggleSound = () => {
    const nextState = !soundEnabled;
    setSoundEnabled(nextState);
    sounds.enabled = nextState;
  };

  return (
    <div className="min-h-screen bg-neutral-950 text-neutral-100 flex flex-col font-sans selection:bg-amber-500 selection:text-black">
      {/* Top Navigation */}
      <Navbar
        activeTab={activeTab}
        onSelectTab={setActiveTab}
        completedCount={completedMilestoneIds.size}
        onOpenWhy={() => setWhyModalOpen(true)}
        soundEnabled={soundEnabled}
        onToggleSound={handleToggleSound}
      />

      {/* Main Content View */}
      <main className="flex-1 max-w-6xl w-full mx-auto px-4 sm:px-6 py-6 sm:py-8">
        {activeTab === 'gacha' && (
          <DailyGacha
            currentMilestone={{
              ...currentMilestone,
              isCompleted: completedMilestoneIds.has(currentMilestone.id)
            }}
            onDrawMilestone={setCurrentMilestone}
            onOpenComplete={(m) => setCompleteModalMilestone(m)}
          />
        )}

        {activeTab === 'constellation' && (
          <ConstellationMap
            completedMilestoneIds={completedMilestoneIds}
            onOpenComplete={(m) => setCompleteModalMilestone(m)}
            onSelectMilestoneForTimer={(m) => {
              setCurrentMilestone(m);
              setActiveTab('gacha');
            }}
          />
        )}

        {activeTab === 'explorer' && (
          <DomainExplorer
            completedMilestoneIds={completedMilestoneIds}
            onOpenComplete={(m) => setCompleteModalMilestone(m)}
            onSelectMilestoneForTimer={(m) => {
              setCurrentMilestone(m);
              setActiveTab('gacha');
            }}
            onOpenAIGenerator={(domain) => setAiGeneratorDomain(domain)}
          />
        )}

        {activeTab === 'sheet' && (
          <GoogleSheetTable
            records={records}
            allMilestones={allMilestones}
            onUpdateRecord={handleUpdateRecord}
            onDeleteRecord={handleDeleteRecord}
            onOpenCompleteModal={(m) => setCompleteModalMilestone(m)}
          />
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-neutral-900 bg-neutral-950 py-6 text-center text-xs text-neutral-500">
        <div className="max-w-6xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-3">
          <p>
            MÁY ĐẺ 1000 MILESTONE Ở TRỌ SÀI GÒN • Công thức: [Hành động 10 phút] + [Ở đâu] + [Thưởng biến đổi]
          </p>
          <div className="flex items-center gap-4 text-neutral-400">
            <button
              onClick={() => setWhyModalOpen(true)}
              className="hover:text-amber-400 underline transition-colors"
            >
              Triết lý 3 WHY
            </button>
            <span>•</span>
            <button
              onClick={() => setActiveTab('sheet')}
              className="hover:text-emerald-400 underline transition-colors"
            >
              Bảng 4 Cột
            </button>
          </div>
        </div>
      </footer>

      {/* Modals */}
      <WhyModal
        isOpen={whyModalOpen}
        onClose={() => setWhyModalOpen(false)}
      />

      <CompleteModal
        milestone={completeModalMilestone}
        isOpen={Boolean(completeModalMilestone)}
        onClose={() => setCompleteModalMilestone(null)}
        onSave={handleSaveComplete}
      />

      <AIGeneratorModal
        isOpen={Boolean(aiGeneratorDomain)}
        onClose={() => setAiGeneratorDomain(null)}
        initialDomain={aiGeneratorDomain}
        onAddCustomMilestones={handleAddCustomMilestones}
      />
    </div>
  );
}
